### PR TITLE
Disable coloring if not attached to a terminal

### PR DESCRIPTION
**Pull request by matze**
Otherwise redirecting the log output to a file will mess up the output.

### CODE REVIEW

**Comment by matze** [comment]
Hmm, weird. On my machine `tox` runs through with both 2.7 and 3.4.

**Comment by fordhurley** [comment]
Probably because travis-ci isn't attached to a terminal. I think it would be better to move the `isatty` checks up somewhere earlier, if anywhere. Personally, I prefer letting the user put that check in, and they can decide whether or not to use color. Something like:

    if sys.stderr.isatty():
        log_format = '%(asctime)s %(bold)s[%(name)s]%(reset)s %(log_color)s%(levelname)s - %(message)s'
        formatter = colorlog.ColoredFormatter(log_format, log_colors=log_colors)
    else:
        log_format = ''%(asctime)s [%(name)s] %(levelname)s - %(message)s'
        formatter = logging.Formatter(log_format)

Also note that I'm checking `stderr`, which is the default output for most loggers.

**Comment by matze** [comment]
> Personally, I prefer letting the user put that check in, and they can decide whether or not to use color.

I configure my loggers with a config file which makes this unwieldy (yes, of course I could set up two formatters but …). Ideally, I'd never would have to decide something like that in order to make things work.

**Comment by borntyping** [comment]
The `colorlog.ColoredFormatter` class doesn't know where the messages it prints are sent, making it somewhat impractical to check if the stream those messages are written to is a TTY. Changing that class would potentially break things for existing users.

I think the most practical way to accomplish this would be to either decide at runtime which formatter to use, or to have a `logging.handlers.StreamHandler` subclass that filters escape codes based on whether it's stream is a TTY. The latter would work with any standard logging configuration method.

**Comment by matze** [comment]
> I think the most practical way to accomplish this would be to either decide at runtime which formatter to use, or to have a logging.handlers.StreamHandler subclass that filters escape codes based on whether it's stream is a TTY.

I like the latter idea. Would this be a reasonable addition to python-colorlog?

**Comment by borntyping** [comment]
> I like the latter idea. Would this be a reasonable addition to python-colorlog?

Yes, that would work. There are a few ways I can think of this might be done, actually:

- A `StreamHandler` subclass could simply filter out escape codes if it's not writing to a TTY (a little hacky, but also the simplest option).

- It might be possible for a `Handler` to switch between multiple formatters based on the stream being a TTY, but I don't know if that can be made to work with the configuration loaders (would mean defining the format twice).

- The `ColoredFormatter` could implement some way to enable/disable colors when formatting a message, and then a `StreamHandler` subclass could pass that information to `.format()` as an extra optional parameter (most complex, but also not as flawed as the other options).

**Comment by matze** [comment]
I added the first option although as you say it's hacky. The last option also has a flaw: if one replaces the colored formatter by something else and keeps the subclassed `StreamHandler`, passing the additional parameter to `format` will break things.

**Comment by borntyping** [comment]
> I added the first option although as you say it's hacky.

Thanks :smiley: I'll look at releasing it as a `-pre` or `-dev` version as soon as I have time, and then seeing if I can implement one of the latter options.

> The last option also has a flaw: if one replaces the colored formatter by something else and keeps the subclassed StreamHandler, passing the additional parameter to format will break things.

I think this can be avoided by checking the type of the formatter when calling `.format()`.

**Comment by borntyping** [comment]
Sorry this has been forgotten about. I've gone back and use a different solution - a `ColoredFormatter` subclass that does not insert color codes if STDOUT (or another given stream) is not a TTY. This should be a bit simpler to use than a filtered stream.

**Pull request closed without merging**
